# Generated by Django 4.1.4 on 2022-12-20 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_hubs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Synopsis',
            new_name='Article',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='category',
            new_name='article',
        ),
    ]
