# Generated by Django 4.1.4 on 2022-12-20 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_hubs', '0002_rename_synopsis_article_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name_plural': 'articles'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article',
            new_name='category',
        ),
    ]
