# Generated by Django 4.1.4 on 2022-12-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_hubs', '0003_alter_article_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
